ANDROID: selftests/memfd: fix duplicate semun definition
Android's bionic provides the 'union semun' definition via <sys/sem.h>
header (and glibc does not). A second definition was introduced in
commit b24335521de9 ("selftests/memfd: use IPC semaphore instead of
SIGSTOP/SIGCONT") breaking Android builds:

 tools/testing/selftests/memfd/memfd_test.c:45:7: error: redefinition of 'semun'
   45 | union semun {
      |       ^
  toolchains/llvm/prebuilt/linux-x86_64/sysroot/usr/include/sys/sem.h:46:7: note: previous definition is here
   46 | union semun {
      |       ^

I tried switching to <linux/sem.h> which provides this definition but
there are further conflicts with other headers. This is likely the
reason why the patch author used <sys/sem.h> instead.

While a better approach is fixed upstream, let's simply avoid the
definition for Android builds for now.

Bug: 504071052
Fixes: b24335521de9 ("selftests/memfd: use IPC semaphore instead of SIGSTOP/SIGCONT")
Change-Id: Ie6081da44179f2e84e99782d1b3fa5c45e55390f
Signed-off-by: Carlos Llamas <cmllamas@google.com>
GitOrigin-RevId: f32ca52507e06b1f8736d2c17e45be2521e269e5